const petsList = [
	{
		id: 'id hash 1',
		owner: 'owner hash 1',
		name: 'nome 1',
		sex: 'f',
		age: 1,
		breed: 'raça 1',
	},
	{
		id: 'id hash 2',
		owner: 'owner hash 2',
		name: 'nome 2',
		sex: 'm',
		age: 2,
		breed: 'raça 2',
	},
	{
		id: 'id hash 3',
		owner: 'owner hash 3',
		name: 'nome 3',
		sex: 'f',
		age: 3,
		breed: 'raça 3',
	},
	{
		id: 'id hash 4',
		owner: 'owner hash 4',
		name: 'nome 4',
		sex: 'm',
		age: 4,
		breed: 'raça 4',
	},
	{
		id: 'id hash 5',
		owner: 'owner hash 5',
		name: 'nome 5',
		sex: 'f',
		age: 5,
		breed: 'raça 5',
	},
];

const postsList = [
	{
		id: 'id hash 1',
		owner: 'owner hash 1',
		title: 'title 1',
		descrip: 'description 1',
		category: 'a',
		sex: 'm',
		breed: 'breed 1',
	},
	{
		id: 'id hash 2',
		owner: 'owner hash 2',
		title: 'title 2',
		descrip: 'description 2',
		category: 'c',
		sex: 'f',
		breed: 'breed 2',
	},
	{
		id: 'id hash 3',
		owner: 'owner hash 3',
		title: 'title 3',
		descrip: 'description 3',
		category: 'a',
		sex: 'm',
		breed: 'breed 3',
	},
	{
		id: 'id hash 4',
		owner: 'owner hash 4',
		title: 'title 4',
		descrip: 'description 4',
		category: 'c',
		sex: 'f',
		breed: 'breed 4',
	},
	{
		id: 'id hash 5',
		owner: 'owner hash 5',
		title: 'title 5',
		descrip: 'description 5',
		category: 'a',
		sex: 'm',
		breed: 'breed 5',
	},
];
